general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/one-dark.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
decorations = "None"
# opacity = 0.9

# [window.padding]
# x=6
# y=6

[font]
size=11.5

[font.normal]
family="JetBrainsMono Nerd Font Mono"

[cursor.style]
shape="Block"
blinking="Always"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    { key = "Space", mods = "Shift", mode = "~Search", action = "ToggleViMode" },
    # { key = "Space", mods = "Control|Shift", mode = "~Search", action = "ToggleViMode" },
]
